- .rubocop.yml
- .travis.yml
- Gemfile.lock
- ckb-sdk-ruby.gemspec
- lib/ckb.rb
- lib/ckb/api.rb
- lib/ckb/blake2b.rb
- lib/ckb/rpc.rb
- lib/ckb/utils.rb
- lib/ckb/wallet.rb
- spec/ckb/api_spec.rb
- spec/ckb/utils_spec.rb
1. add basic wallet
2. rename `RPC` to `API`
> feat: add basic wallet

- lib/ckb/api.rb
- lib/ckb/utils.rb
- lib/ckb/wallet.rb
- spec/ckb/api_spec.rb
- spec/ckb/utils_spec.rb
This commit captures 2 changes:
* It updates the SDK following latest Script refactoring
* It as a new mode in API to automatically load correct lock script in
case testnet spec is used
> feat: Upgrade SDK with latest CKB changes

- lib/bech32.rb
- lib/ckb.rb
- lib/ckb/api.rb
- lib/ckb/convert_address.rb
- lib/ckb/utils.rb
- lib/ckb/wallet.rb
- spec/ckb/api_spec.rb
- spec/ckb/utils_spec.rb
1. address format
2. use new script which only has SIGHASH_ALL type
3. only use hex string in SDK
> feat: Address format implementation

- lib/ckb/api.rb
- lib/ckb/transaction.rb
- lib/ckb/utils.rb
- lib/ckb/wallet.rb
- spec/ckb/api_spec.rb
- spec/ckb/utils_spec.rb
https://github.com/nervosnetwork/ckb/pull/533
> refactor: rename variables

- CHANGELOG.md
- Gemfile.lock
- lib/ckb/version.rb
1. update version to 0.11.0
2. update CHANGELOG for v0.11.0
> [ᚬrc/v0.11.0] docs: update CHANGELOG for v0.11.0

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- lib/ckb/types/block_header.rb
- lib/ckb/types/epoch.rb
- lib/ckb/types/types.rb
- spec/ckb/api_spec.rb
1. add `Types::Epoch`
2. add RPC `get_current_epoch`
3. add `epoch` attribute to `Types::BlockHeader`
> feat: add epoch type and add `get_current_epoch` RPC

- lib/ckb/api.rb
- lib/ckb/types/address_info.rb
- lib/ckb/types/peer.rb
- lib/ckb/types/tx_pool_info.rb
- lib/ckb/types/types.rb
- spec/ckb/api_spec.rb
- spec/ckb/types/peer_spec.rb
- spec/ckb/types/tx_pool_info_spec.rb
1. add `TxPoolInfo` , `Peer` and `AddressInfo` types
2. change `tx_pool_info`, `local_node_info`, and `get_peers` to return types instead of `Hash`
> feat: add more types

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- lib/ckb/types/script.rb
- lib/ckb/types/transaction.rb
- lib/ckb/wallet.rb
This PR updates SDK per script changes at https://github.com/nervosnetwork/ckb-system-scripts/pull/12
> feat: update SDK per lock script changes

- lib/ckb/types/block.rb
- lib/ckb/types/block_header.rb
- lib/ckb/types/input.rb
- lib/ckb/types/output.rb
- lib/ckb/types/seal.rb
- lib/ckb/types/transaction.rb
- lib/ckb/types/transaction_with_status.rb
- lib/ckb/types/tx_status.rb
- lib/ckb/types/types.rb
- lib/ckb/types/uncle.rb
- lib/ckb/types/witness.rb
Add more comment to types initialize to make it more clear
> chore: make types initialize attrs type same to RPC

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- spec/ckb/rpc_spec.rb
BREAKING CHANGE: trace RPCs are deleted
> perf: remove trace RPCs

- lib/ckb/types/transaction.rb
NOTE: this should be on hold till https://github.com/nervosnetwork/ckb/pull/723 is merged.
> feat: remove unneeded blake2b hash

- lib/ckb/api.rb
- spec/ckb/api_spec.rb
- spec/ckb/rpc_spec.rb
https://github.com/nervosnetwork/ckb/pull/745
> feat: update system script cell index to 1

- lib/ckb/types/transaction.rb
> refactor: Reuse computed data for witness now that all witnesses

- CHANGELOG.md
- Gemfile.lock
- lib/ckb/version.rb
1. update version to `0.12.0`
2. add `v0.12.0` changelog
> [ᚬrc/v0.12.0] Rc/v0.12.0 changelog

- Gemfile.lock
https://rubygems.org/gems/ffi/versions/1.11.0
> fix: update ffi version

- README.md
> docs: Update libsecp256k1 install guide for Ubuntu

- lib/ckb/types/tx_pool_info.rb
- spec/ckb/types/tx_pool_info_spec.rb
Add `total_tx_cycles` and `total_tx_size` to `TxPoolInfo`
> feat: add two attrs to `TxPoolInfo`

- .gitignore
- .travis.yml
- Gemfile.lock
- README.md
- Rakefile
- bin/setup
- ckb-sdk-ruby.gemspec
- config/warble.rb
- exe/ckb-console
- lib/ckb-sdk-ruby_jars.rb
- lib/ckb.rb
- lib/ckb/blake2b.rb
- lib/ckb/key.rb
- lib/ckb/platform/java/blake2b.rb
- lib/ckb/platform/java/key.rb
- lib/ckb/platform/ruby/blake2b.rb
- lib/ckb/platform/ruby/key.rb
- lib/ckb/rpc.rb
- lib/ckb/types/transaction.rb
- lib/ckb/utils.rb
- lib/ckb/wallet.rb
- spec/ckb/key_spec.rb
Ease deployment by providing a single jar with all the depdencies.
Try it:
First install and switch to JRuby, then
```
bin/setup
bundle exec rake jar
java -jar ckb-console-0.12.2.jar
```
> feat: jruby and warble support

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- lib/ckb/types/cell_transaction.rb
- lib/ckb/types/live_cell.rb
- lib/ckb/types/lock_hash_index_state.rb
- lib/ckb/types/transaction_point.rb
- lib/ckb/types/types.rb
- spec/ckb/api_spec.rb
- spec/ckb/rpc_spec.rb
ref: https://github.com/nervosnetwork/ckb/pull/905/files#diff-622e6d119ac5d43f7eb41cb596159f9fR797
> feat: add indexer RPCs

- lib/ckb/types/epoch.rb
- spec/ckb/types/epoch_spec.rb
ref: https://github.com/nervosnetwork/ckb/pull/1088
> chore: update epoch schema

- lib/ckb/api.rb
- lib/ckb/types/script.rb
- spec/ckb/types/script_spec.rb
The new structure is introduced in https://github.com/nervosnetwork/ckb/pull/1165
> feat: Add hash type per CKB changes

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- lib/ckb/types/block_reward.rb
- lib/ckb/types/types.rb
- spec/ckb/api_spec.rb
- spec/ckb/rpc_spec.rb
```
1. get_header
2. get_header_by_number
3. get_cellbase_output_capacity_details
```
> feat: add new RPCs

- lib/ckb/api.rb
- lib/ckb/serializers/cell_dep_serializer.rb
- lib/ckb/serializers/input_serializer.rb
- lib/ckb/serializers/out_point_serializer.rb
- lib/ckb/serializers/raw_transaction_serializer.rb
- lib/ckb/serializers/serializers.rb
- lib/ckb/serializers/struct_serializer.rb
- spec/ckb/types/transaction_spec.rb
1. use struct serializer replace some table serializer.
2. update expected `code_hash` and `type_hash`.
3. add more tests.
> feat: use struct serializer replace some table serializer

- lib/ckb/address.rb
- spec/ckb/address_spec.rb
merge two type address parser to one
> refactor: address parse

- lib/ckb/api.rb
- lib/ckb/wallet.rb
https://github.com/nervosnetwork/ckb-system-scripts/pull/45
> [ᚬrc/v0.22.0] feat: update NervosDAO lock period to 180 epochs

- CHANGELOG.md
- Gemfile.lock
- lib/ckb/types/transaction.rb
- lib/ckb/version.rb
- lib/ckb/wallet.rb
- spec/ckb/types/transaction_size_spec.rb
* add fee to dao ([c5a8ee4](https://github.com/nervosnetwork/ckb-sdk-ruby/commit/c5a8ee4b2e7b0e501bdde60550668c9dc7867199))
> [ᚬmaster] Rc/v0.23.1

- lib/ckb/cell_collector.rb
- lib/ckb/multi_sign_wallet.rb
- lib/ckb/wallet.rb
BREAKING CHANGE: remove min_capacity in gather_inputs
> fix: InsufficientCellCapacity when collect cells

- CHANGELOG.md
- Gemfile.lock
- lib/ckb/version.rb
> [ᚬmaster] Rc/v0.28.0

- CHANGELOG.md
- Gemfile.lock
- lib/ckb/version.rb
* Bump rake to 13.0.1Bump rake to 13.0.1
> [ᚬmaster] Rc/v0.29.1

- lib/ckb/api.rb
- lib/ckb/rpc.rb
- lib/ckb/types/block_economic_state.rb
- lib/ckb/types/block_issuance.rb
- lib/ckb/types/miner_reward.rb
- lib/ckb/types/tx_pool_info.rb
- lib/ckb/types/types.rb
- spec/ckb/api_spec.rb
- spec/ckb/rpc_spec.rb
- spec/ckb/types/tx_pool_info_spec.rb
1. add `get_block_economic_state` RPC.
2. add min_fee_rate on `tx_pool_info` RPC.
> feat: add new rpc

- CHANGELOG.md
- lib/ckb/version.rb
> chore: Bump version to v0.38.0
